# Generated by Django 5.0.7 on 2024-08-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdbId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('coverURL', models.TextField()),
                ('releaseDate', models.TextField()),
                ('associations', models.IntegerField()),
            ],
        ),
    ]
