# Generated by Django 5.0.7 on 2024-08-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_post_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlistId',
            field=models.CharField(default='ERROR', max_length=200),
        ),
    ]
