# Generated by Django 5.0.7 on 2024-08-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_playlist_playlistid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='body',
        ),
        migrations.AddField(
            model_name='playlist',
            name='caption',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(default='Why is this playlist awesome for this game?'),
        ),
    ]
