# Generated by Django 5.0.7 on 2024-08-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_playlist_body_playlist_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlistId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
