# Generated by Django 5.0.7 on 2024-08-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_playlist_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.JSONField(default=dict),
        ),
    ]
