# Generated by Django 5.0.7 on 2024-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_playlist_banner_playlist_bannerurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='gameIds',
            field=models.TextField(default=''),
        ),
    ]
